name: Validate OpenApi spec with optional stack selection
description: Read SST API URL and validate OpenApi spec
inputs:
  stack-name:
    description: SST Stack name to get API URL from (optional - if not provided, returns first available API URL)
    required: false
  openapi-url:
    description: OpenApi URL
    required: true
    default: /openapi.yaml
  retries:
    description: Number of retries
    required: false
    default: '4'
runs:
  using: composite
  steps:
    - name: Read SST API URL for stack
      shell: bash
      id: sst-url
      run: |
        if [[ -n "${{ inputs.stack-name }}" ]]; then
          API_URL=$(STACK_NAME="${{ inputs.stack-name }}" pnpm output:read | tail -n 1 | tr -d '[:space:]')
          STACK_INFO="for stack ${{ inputs.stack-name }}"
        else
          API_URL=$(pnpm output:read | tail -n 1 | tr -d '[:space:]')
          STACK_INFO="(first available)"
        fi
        # Remove trailing slash if present
        API_URL=${API_URL%/}
        if [[ -z "$API_URL" ]]; then
          echo "API_URL is empty ${STACK_INFO}. Exiting..."
          exit 1
        fi
        echo "API_URL=$API_URL" >> "$GITHUB_OUTPUT"
        echo "Found API URL ${STACK_INFO}: $API_URL"
    - name: Wait for SST API URL
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/url-check.sh
        ${{ github.action_path }}/url-check.sh
      env:
        URL: ${{ steps.sst-url.outputs.API_URL }}${{ inputs.openapi-url }}
        MAX_RETRIES: ${{ inputs.retries }}
    - name: Validate OpenApi spec
      shell: bash
      run: |
        chmod +x .github/scripts/openapi-check.sh
        .github/scripts/openapi-check.sh
