name: Publish Test Results
description: Publish test results and Allure report to GitHub Pages
inputs:
  files:
    description: File patterns of test result files
    required: true
  allure_results:
    description: Path to the Allure results directory
    required: true
  github_token:
    description: GitHub token to use for the commit
    required: true
runs:
  using: composite
  steps:
    - name: Publish Test Results
      id: test-results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: ${{ inputs.files }}
        check_run: false
        job_summary: false
        comment_title: WDIO Test Results
        action_fail_on_inconclusive: true
    - name: Get Test Conclusion
      shell: bash
      id: test-conclusion
      run: echo "conclusion=$(jq -r '.conclusion' <<< '${{ steps.test-results.outputs.json }}')" >> $GITHUB_OUTPUT
    - name: Check for gh-pages branch
      if: steps.test-conclusion.outputs.conclusion != 'success'
      shell: bash
      run: |
        if ! git ls-remote --exit-code --heads origin gh-pages; then
          git checkout --orphan gh-pages
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi
    - name: Load Allure report history
      if: steps.test-conclusion.outputs.conclusion != 'success'
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Build Allure report
      if: steps.test-conclusion.outputs.conclusion != 'success'
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: ${{ inputs.allure_results }}
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Publish Allure report
      if: steps.test-conclusion.outputs.conclusion != 'success'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_branch: gh-pages
        publish_dir: allure-history
